### ISSUE TITLE
Font Placing On Ubuntu Gnome 17.04

### ISSUE THREAD

**Issue by stefan-reich** [kirill-grouchnikov/substance#30] opened 2017-07-06 18:04 UTC
Hi, I'm evaluating Ubuntu Gnome 17.04 for Java-related problems. System tray is one issue. The other is the unusually large fonts, apparently, which screw up some of the design (the vertical tabs):

![Screenshot](http://eyeocr.sourceforge.net/filestore/filestore.php?cmd=serve&file=blob_1009158&contentType=image/png)

This is a freshly installed Ubuntu running the Substance-based application.

Is this known? Should I try to upgrade the Substance version I'm using?

[Program](http://tinybrain.de:8080/tb/show-snippet.php?id=1000825)

Cheers,
Stefan

**Comment by kirill-grouchnikov** [comment] 2017-07-06 18:08
I don't have access to Gnome environment. DefaultGnomeFontPolicy is the font policy for that desktop, and you can trace the execution there to see where the font size is derived.

As for the right-hand tabs, that doesn't seem to be related to the font size. I'm not seeing any text placement issues on right-hand tabs on my Mac under the latest 7.1 dev builds. Which version of Substance are you running? Is this tab text issue happening only on Gnome?

**Comment by stefan-reich** [comment] 2017-07-06 18:12
I think the font is in line with Gnome's fonts (see "Activities" in the
top-left corner). So, not a problem there. Just the placement inside the
tab is weird. I can try a later Substance version, indeed I am using one
from 11/2016.

On Thu, Jul 6, 2017 at 8:09 PM, Kirill Grouchnikov <notifications@github.com

**Comment by kirill-grouchnikov** [comment] 2017-07-06 18:15
The rotation of left / right tabs is happening in SubstanceTabbedPaneUI.paintTab. I don't think I've touched that code after coming back from the hiatus. Wouldn't hurt checking it under the latest dev bits, of course.

But if it's still happening, and only happening under Gnome, then I won't be able to do much, unfortunately.

**Comment by kirill-grouchnikov** [comment] 2017-10-17 02:26
Is this still happening under the latest bits? Version 7.1.00 just went live.

**Comment by utybo** [comment] 2017-10-27 20:41
Yes, this still happens under the latest Gnome version, the issue is the same.

**Comment by kirill-grouchnikov** [comment] 2017-10-27 21:08
I'll have to defer the debugging of this one to people who have this setup. The relevant code that "rotates" the graphics for those tabs is in SubstanceTabbedPaneUI.paintTab, lines 1558-1565.

**Comment by utybo** [comment] 2018-03-18 20:07
I have more information on this issue as I just had it happen to me

This is a JRE bug, that is present in the 8u60 Java version (the default one available from the repositories of Ubuntu 16.04) but is fixed in the latest Java 8 releases.

@kirill-grouchnikov you can probably close this

**Comment by kirill-grouchnikov** [comment] 2018-03-27 15:49
Closing based on the latest comment and no activity from the OP.

**Closed by kirill-grouchnikov** 2018-03-27 15:49 UTC
